// front-end/student-react/src/components/student/Student.jsx
import React, { Component} from "react";
import "./Student.css";
import axios from "axios";
import ShowEditForm from "../ShowEditForm/ShowEditForm";
import Pagination from "../Pagination/Pagination";
const baseURL = "http://localhost:8080/api/v1/student";

export default class Student extends Component {
  
  
  constructor(props) {
    super(props);
    this.state = {
      students: []
    };

    // const [showForm, setShowForm] = useState(false);
    // const [show, setShow] = useState();


    // *http Request : GET
    axios.get(baseURL).then((response) => {
      const students = response.data;
      this.setState({ students });
    });
  }

  DeleteStudent(id,e) {
    axios.delete(`http://localhost:8080/api/v1/student/${id}`)
    .then(response => console.log(response));
    const students = this.state.students.filter(item => item.id !== id);  
    this.setState({ students });  
    }

  ButtonToShowEditForm(){ 
    console.log("Edit Form showed !");
  }


  render() {
    return (
      <div>
        <div className="container">
          <div className="col card row bg-transparent solid-gray">
            <div className="card-body">
              <h4 style={{ textAlign: "center" }} className="card-title">
                List of students
              </h4>
              <div className="row col-2">
                <button onClick={() => this.ButtonToShowEditForm()} className="btn btn-success">
                  <span className="fa fa-plus"></span> ADD
                </button>
              </div>
              <br />
              <div>
              <ShowEditForm />
              </div>
              <hr />
            </div>
            <ul className="list-group list-group-flush">
              {this.state.students.map((student) => {
                return (
                  <div key={student.id}>
                    <ul className="list-group-item list-group-item-action list-group-item-secondary">
                      <li>Id : {student.id}</li>
                      <li>Name : {student.name}</li>
                      <li>Email : {student.email}</li>
                      <li>Date of birthday : {student.dob}</li>
                      <li>Age : {student.age}</li>
                      <br />
                      <div className="row col">
                        <div className="col-2">
                          <button
                            onClick={(e) =>this.DeleteStudent(student.id,e)}
                            className="btn btn-danger">
                            <span className="fa fa-trash"></span> DELETE
                          </button>
                        </div>
                        <div className="col-2">
                          <button className="btn btn-warning">
                            <span className="fa fa-refresh"></span> UPDATE
                          </button>
                        </div>
                      </div>
                    </ul>
                    <br />
                  </div>
                );
              })}
            </ul>
          </div>
        </div>
      </div>
    );
  }
}

// front-end/src/app/components/student/student.component.ts
import { Component, OnInit } from '@angular/core';
import { Student } from 'src/app/models/student';
import { StudentServiceService } from 'src/app/services/student-service.service';

@Component({
  selector: 'app-student',
  templateUrl: './student.component.html',
  styleUrls: ['./student.component.css']
})
export class StudentComponent implements OnInit{

  searchStudent:any;
  showForm = false;
  students: any;
  student: any;
  id:any;
  myStudent: Student ={
    name: '',
    email: '',
    dob: '',
    age: 0
  }

  constructor(private studentService: StudentServiceService) { }

  ngOnInit() {
    this.studentService.findAll().subscribe(students => {
      this.students = students
    });
}

// findByStudentId(){
//   console.log("Find by student ID method called");
//   console.log(this.studentService.findAll(this.id).subscribe(data => {
//     this.data = data;
//   }));


// }

// ! The delete method is when the button is clicked
deleteStudent(id: number){
  if (confirm("Are you sure to delete student !")) {
    this.studentService.deleteById(id).subscribe(
      () => {
        this.students = this.students.filter((student: { id: number; }) => student.id != id)
      }
    );
  }
  this.ngOnInit();
}


    //Called after the constructor, initializing input properties, and the first call to ngOnChanges.
    //Add 'implements OnInit' to the class.


addStudent(){
  this.studentService.addNewStudent(this.myStudent).subscribe((student) => {
    this.students = [student, ...this.students]
  });
  this.ngOnInit();
}

}

<!-- <p>student works!</p> -->

<!-- ! division is for label of search -->

<div class="container">
<div class="row">
  <div>
        <i class="fa fa-search fa-lg"></i>
        <span>
          <input type="text" style="margin-left: 1em" [(ngModel)]="searchStudent" placeholder="Search...">
        </span>
    </div>
  </div>
</div>
<br>

<!-- ! division is for show form of adding student -->
<div class="container col-12">
  <div class="row">

    <div class="col-md-6">
      <h3>List of Students :</h3>
    </div>
    <div class="col-md-6 text-end">
      <button class="btn btn-dark btn-sm" (click)="showForm = !showForm">
        <i class="fa fa-plus"></i> New Student
      </button>
    </div>
  </div>

  <!--! label for add new student -->
  <div class="card" *ngIf="showForm">
    <div class="form-group card-body">
      <!-- Name -->
      <label for="name">
        <i class="fa fa-graduation-cap"> Name : </i>
      </label>
      <input [(ngModel)]="myStudent.name" id="name" type="text" class="form-control" />

      <!-- Email -->
      <label for="e-mail">
        <i class="fa fa-envelope"> E-mail : </i>
      </label>
      <input [(ngModel)]="myStudent.email" id="e-mail" type="email" class="form-control" />

      <!-- Date of birthday -->
      <label for="dob">
        <i class="fa fa-birthday-cake"> Date of birthday : </i>
      </label>
      <input [(ngModel)]="myStudent.dob" id="dob" type="date" class="form-control" />

      <!-- Age -->
      <label for="age">
        <i class="fa fa-clock-o"> Age : </i>
      </label>
      <input [(ngModel)]="myStudent.age" id="age" type="number" class="form-control" />
    </div>
    <div class="card-footer">
      <button (click)="addStudent()" class="btn btn-success btn-block mx-sm-3">
        <i class="fa fa-graduation-cap"> Add new student </i>
      </button>
    </div>
  </div>

  <br />

  <!--! this division for show list data student from database    -->
  <div class="card-deck">
    <ul class="list-group">
      <li
        *ngFor="let student of students | filter:searchStudent"
        class="list-group-item list-group-item-action list-group-item-dark"
      >
        Student ID : {{ student.id }}
        <br />
        Name : {{ student.name }}
        <br />
        Email : {{ student.email }}
        <br />
        Date of birthday : {{ student.dob }}
        <br />
        Age : {{ student.age }}
        <br />
        <br />
        <div class="row-cols-6">
          <button class="btn btn-sm btn-danger" (click)="deleteStudent(student.id)" style="margin-left: 10px">
            <i class="fa fa-trash"></i>
          </button>
          <button class="btn btn-sm btn-warning" style="margin-left: 10px">
            <i class="fa fa-pencil"></i>
          </button>
        </div>
      </li>
    </ul>
  </div>
</div>
